name: apiverve_jsonschemagenerator
description: JSON Schema Generator is a tool for automatically generating JSON schemas from sample JSON data. It creates Draft-07 compatible schemas with type inference and format detection.
version: 1.1.14
homepage: https://apiverve.com/marketplace/jsonschemagenerator?utm_source=dart&utm_medium=homepage
repository: https://github.com/apiverve/jsonschemagenerator-api/tree/main/dart

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  http_parser: ^4.0.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
