// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var responseObj = ResponseObj.FromJson(jsonString);

namespace APIVerve.API.JSONSchemaGenerator
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class ResponseObj
    {
        [JsonProperty("status")]
        public string Status { get; set; }

        [JsonProperty("error")]
        public object Error { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }
    }

    public partial class Data
    {
        [JsonProperty("schema")]
        public Schema Schema { get; set; }

        [JsonProperty("sample_data")]
        public SampleData SampleData { get; set; }
    }

    public partial class SampleData
    {
        [JsonProperty("name")]
        public string Name { get; set; }

        [JsonProperty("age")]
        public long Age { get; set; }

        [JsonProperty("email")]
        public string Email { get; set; }

        [JsonProperty("active")]
        public bool Active { get; set; }
    }

    public partial class Schema
    {
        [JsonProperty("$schema")]
        public Uri SchemaSchema { get; set; }

        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("properties")]
        public Properties Properties { get; set; }

        [JsonProperty("required")]
        public string[] SchemaRequired { get; set; }
    }

    public partial class Properties
    {
        [JsonProperty("name")]
        public Active Name { get; set; }

        [JsonProperty("age")]
        public Active Age { get; set; }

        [JsonProperty("email")]
        public Email Email { get; set; }

        [JsonProperty("active")]
        public Active Active { get; set; }
    }

    public partial class Active
    {
        [JsonProperty("type")]
        public string Type { get; set; }
    }

    public partial class Email
    {
        [JsonProperty("type")]
        public string Type { get; set; }

        [JsonProperty("format")]
        public string Format { get; set; }
    }
}
